mainConfig:
  type: esbuild
  path: esbuild.main.config.js
  src: src/main/main.ts
  output: dist/main
rendererConfig:
  type: vite
  path: vite.config.js
  src: src/renderer/main.ts
  output: dist/renderer
